In [2]:
import numpy as np

In [1]:
import array

In [5]:
type(np.array([1,2,3,5]))

numpy.ndarray

In [1]:
import numpy as np
import pandas as pd

ModuleNotFoundError: No module named 'numpy'

In [7]:
a = np.array([[[1,3],[3,4]],[[1,3],[3,4]]])

In [10]:
a.shape

(2, 2, 2)

In [11]:
np.

<function numpy.lib.utils.who(vardict=None)>

In [81]:
np.array([1,2,3])

array([1, 2, 3])

In [18]:
b = np.mat(np.array([[1,3],[3,4]]))

In [27]:
l = (np.array(([1,3],[3,4])))

In [31]:
np.asanyarray(b)

matrix([[1, 3],
        [3, 4]])

In [30]:
np.asarray(b)

array([[1, 3],
       [3, 4]])

In [32]:
issubclass(np.matrix , np.ndarray)

True

In [36]:
l

array([[1, 3],
       [3, 4]])

In [37]:
a = l

In [38]:
a

array([[1, 3],
       [3, 4]])

In [39]:
b = np.copy(l)

In [40]:
b

array([[1, 3],
       [3, 4]])

In [41]:
l[0][0]=67

In [42]:
l

array([[67,  3],
       [ 3,  4]])

In [43]:
a

array([[67,  3],
       [ 3,  4]])

In [44]:
b

array([[1, 3],
       [3, 4]])

In [45]:
1a[-1]

SyntaxError: invalid syntax (<ipython-input-45-d7a8b5febd66>, line 1)

In [46]:
a[-1]

array([3, 4])

In [47]:
for i in a :
    print(i)

[67  3]
[3 4]


In [49]:
np.fromfunction(lambda i , j : i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [50]:
np.fromfunction(lambda i , j : i*j,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [51]:
np.fromfunction(lambda i , j : i/j,(4,4))

<ipython-input-51-b2036f6ce812>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i , j : i/j,(4,4))
<ipython-input-51-b2036f6ce812>:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i , j : i/j,(4,4))


array([[       nan, 0.        , 0.        , 0.        ],
       [       inf, 1.        , 0.5       , 0.33333333],
       [       inf, 2.        , 1.        , 0.66666667],
       [       inf, 3.        , 1.5       , 1.        ]])

In [52]:
1/0

ZeroDivisionError: division by zero

In [56]:
gen = (i*i for i in range(5))

In [54]:
def test(x):
    yield x

In [55]:
test(5)

<generator object test at 0x7f251cd34ac0>

In [59]:
np.fromiter(range(5) , dtype= int)

array([0, 1, 2, 3, 4])

In [67]:
x = np.fromiter(gen, dtype= int)

SyntaxError: invalid syntax (<ipython-input-67-6a4f5c5fc64c>, line 1)

In [70]:
np.fromstring('1,2,3,4,4,4,4', sep = ',', dtype= complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 4.+0.j, 4.+0.j, 4.+0.j])

In [71]:
l = [3,4,6,6,66,6]

In [72]:
arr = np.array(l)

In [73]:
arr

array([ 3,  4,  6,  6, 66,  6])

In [74]:
arr1 = [[1,2,3,4], [2,3,4,5],[5,6,7,8]]

In [77]:
arr1 = np.array(arr1)

In [78]:
type(arr1)

numpy.ndarray

In [79]:
arr1.ndim

2

In [82]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [5, 6, 7, 8]])

In [83]:
arr1.size

12

In [84]:
arr1.shape

(3, 4)

In [86]:
arr1.dtype

dtype('int64')

In [87]:
arr1.size

12

In [89]:
arr.shape

(6,)

In [95]:
arr2 = np.array([[[1,2,3,3],[4,5,6,7]],[[1,2,3,3],[4,5,6,7]]])

In [96]:
arr2

array([[[1, 2, 3, 3],
        [4, 5, 6, 7]],

       [[1, 2, 3, 3],
        [4, 5, 6, 7]]])

In [97]:
arr2.size

16

In [98]:
arr2.shape

(2, 2, 4)

In [99]:
arr2.ndim

3

In [101]:
arr3 = np.array([[[[1,2,3,3],[4,5,6,7]],[[1,2,3,3],[4,5,6,7]],[[1,2,3,3],[4,5,6,7]],[[1,2,3,3],[4,5,6,7]]]])

In [102]:
arr3

array([[[[1, 2, 3, 3],
         [4, 5, 6, 7]],

        [[1, 2, 3, 3],
         [4, 5, 6, 7]],

        [[1, 2, 3, 3],
         [4, 5, 6, 7]],

        [[1, 2, 3, 3],
         [4, 5, 6, 7]]]])

In [103]:
arr3.ndim

4

In [104]:
arr3.shape

(1, 4, 2, 4)

In [105]:
np.arange(6.7)

array([0., 1., 2., 3., 4., 5., 6.])

In [109]:
np.arange(8.4, 11,.3)

array([ 8.4,  8.7,  9. ,  9.3,  9.6,  9.9, 10.2, 10.5, 10.8])

In [110]:
np.arange(9, 5 , -0.3)

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6, 6.3, 6. , 5.7, 5.4,
       5.1])

In [111]:
np.linspace(0.1, 0.2 , 20)

array([0.1       , 0.10526316, 0.11052632, 0.11578947, 0.12105263,
       0.12631579, 0.13157895, 0.13684211, 0.14210526, 0.14736842,
       0.15263158, 0.15789474, 0.16315789, 0.16842105, 0.17368421,
       0.17894737, 0.18421053, 0.18947368, 0.19473684, 0.2       ])

In [115]:
np.linspace(0.2, 0.1,20)

array([0.2       , 0.19473684, 0.18947368, 0.18421053, 0.17894737,
       0.17368421, 0.16842105, 0.16315789, 0.15789474, 0.15263158,
       0.14736842, 0.14210526, 0.13684211, 0.13157895, 0.12631579,
       0.12105263, 0.11578947, 0.11052632, 0.10526316, 0.1       ])

In [119]:
np.linspace(1,2, axis=-1)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [120]:
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [121]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [127]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [130]:
np.ones((2,5,4))+5

array([[[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]],

       [[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]]])

In [133]:
np.empty((2,5,7))

array([[[0.00000000e+000, 0.00000000e+000, 4.94065646e-324,
         4.64654868e-310, 3.26083326e-322, 6.90690769e-310,
         6.90690771e-310],
        [6.90690769e-310, 6.90690769e-310, 6.90690769e-310,
         6.90690772e-310, 6.90690770e-310, 6.90690769e-310,
         6.90690771e-310],
        [6.90690811e-310, 6.90690820e-310, 6.90690769e-310,
         6.90690771e-310, 6.90690768e-310, 6.90690787e-310,
         6.90690768e-310],
        [6.90690776e-310, 6.90690776e-310, 6.90690771e-310,
         6.90690773e-310, 6.90690771e-310, 6.90690769e-310,
         6.90690772e-310],
        [6.90690769e-310, 6.90690769e-310, 6.90690769e-310,
         6.90690766e-310, 6.90690766e-310, 6.90690770e-310,
         6.90690766e-310]],

       [[6.90690766e-310, 6.90690766e-310, 6.90690766e-310,
         6.90690766e-310, 6.90690784e-310, 6.90690772e-310,
         6.90690772e-310],
        [6.90690772e-310, 6.90690772e-310, 6.90690772e-310,
         6.90690772e-310, 6.90690771e-310, 6.90690771e-3

In [135]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [146]:
np.linspace([1,8],1, endpoint=False, axis=0)

array([[1.  , 8.  ],
       [1.  , 7.86],
       [1.  , 7.72],
       [1.  , 7.58],
       [1.  , 7.44],
       [1.  , 7.3 ],
       [1.  , 7.16],
       [1.  , 7.02],
       [1.  , 6.88],
       [1.  , 6.74],
       [1.  , 6.6 ],
       [1.  , 6.46],
       [1.  , 6.32],
       [1.  , 6.18],
       [1.  , 6.04],
       [1.  , 5.9 ],
       [1.  , 5.76],
       [1.  , 5.62],
       [1.  , 5.48],
       [1.  , 5.34],
       [1.  , 5.2 ],
       [1.  , 5.06],
       [1.  , 4.92],
       [1.  , 4.78],
       [1.  , 4.64],
       [1.  , 4.5 ],
       [1.  , 4.36],
       [1.  , 4.22],
       [1.  , 4.08],
       [1.  , 3.94],
       [1.  , 3.8 ],
       [1.  , 3.66],
       [1.  , 3.52],
       [1.  , 3.38],
       [1.  , 3.24],
       [1.  , 3.1 ],
       [1.  , 2.96],
       [1.  , 2.82],
       [1.  , 2.68],
       [1.  , 2.54],
       [1.  , 2.4 ],
       [1.  , 2.26],
       [1.  , 2.12],
       [1.  , 1.98],
       [1.  , 1.84],
       [1.  , 1.7 ],
       [1.  , 1.56],
       [1.  ,

In [150]:
np.logspace([2,6],5,axis=1)

array([[1.00000000e+02, 1.15139540e+02, 1.32571137e+02, 1.52641797e+02,
        1.75751062e+02, 2.02358965e+02, 2.32995181e+02, 2.68269580e+02,
        3.08884360e+02, 3.55648031e+02, 4.09491506e+02, 4.71486636e+02,
        5.42867544e+02, 6.25055193e+02, 7.19685673e+02, 8.28642773e+02,
        9.54095476e+02, 1.09854114e+03, 1.26485522e+03, 1.45634848e+03,
        1.67683294e+03, 1.93069773e+03, 2.22299648e+03, 2.55954792e+03,
        2.94705170e+03, 3.39322177e+03, 3.90693994e+03, 4.49843267e+03,
        5.17947468e+03, 5.96362332e+03, 6.86648845e+03, 7.90604321e+03,
        9.10298178e+03, 1.04811313e+04, 1.20679264e+04, 1.38949549e+04,
        1.59985872e+04, 1.84206997e+04, 2.12095089e+04, 2.44205309e+04,
        2.81176870e+04, 3.23745754e+04, 3.72759372e+04, 4.29193426e+04,
        4.94171336e+04, 5.68986603e+04, 6.55128557e+04, 7.54312006e+04,
        8.68511374e+04, 1.00000000e+05],
       [1.00000000e+06, 9.54095476e+05, 9.10298178e+05, 8.68511374e+05,
        8.28642773e+05,

In [151]:
d = np.linspace(4,7 , 40)

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [153]:
d.ndim

1

In [154]:
d.shape

(40,)

In [156]:
e = d.reshape(8,5)

In [164]:
e.reshape(1,4,10)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769],
        [4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923],
        [6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [4]:
np.random.rand(3)

array([0.0010169 , 0.60013749, 0.2502217 ])

In [5]:
np.random.randn(6)

array([ 0.09242002, -1.13963289, -0.71930434,  1.42274804,  1.25994893,
        0.87256692])

In [8]:
np.random.randn(2,2,4)

array([[[-1.97022558, -0.37891126,  0.39487424, -0.09656566],
        [ 0.06853609, -1.05379933, -1.42035122, -1.4787761 ]],

       [[ 0.01555588,  0.23718388,  1.03025685,  1.15605645],
        [-0.08149601, -0.35497914, -0.85874418, -0.11483618]]])

In [12]:
np.random.randint(999)

914

In [13]:
np.random.randint(5,90,(4,4))

array([[69, 35, 23,  6],
       [41, 76, 44, 73],
       [53, 37, 80, 37],
       [24, 60, 11, 10]])

In [15]:
ar = np.random.randint(3,9 , (3,3))

In [16]:
ar.shape

(3, 3)

In [17]:
ar.size

9

In [18]:
ar.reshape(1,9)

array([[7, 4, 8, 5, 5, 5, 4, 4, 5]])

In [19]:
ar.reshape(9,1)

array([[7],
       [4],
       [8],
       [5],
       [5],
       [5],
       [4],
       [4],
       [5]])

In [20]:
ar.reshape(1,1,9)

array([[[7, 4, 8, 5, 5, 5, 4, 4, 5]]])

In [45]:
x = np.random.randint(4,100, (5,5))

In [44]:
x

matrix([[56,  8, 22, 51, 54],
        [62, 63, 51, 77, 47],
        [29, 22, 46, 11, 93],
        [97, 53, 59, 11, 15],
        [94, 75, 88, 74, 24]])

In [25]:
x[3:,3:]

array([[11, 15],
       [74, 24]])

In [29]:
x[:,[1,3]]

array([[ 8, 51],
       [63, 77],
       [22, 11],
       [53, 11],
       [75, 74]])

In [30]:
x[[1,3],:]

array([[62, 63, 51, 77, 47],
       [97, 53, 59, 11, 15]])

In [32]:
x[x>50]

array([56, 51, 54, 62, 63, 51, 77, 93, 97, 53, 59, 94, 75, 88, 74])

In [33]:
x*x

array([[3136,   64,  484, 2601, 2916],
       [3844, 3969, 2601, 5929, 2209],
       [ 841,  484, 2116,  121, 8649],
       [9409, 2809, 3481,  121,  225],
       [8836, 5625, 7744, 5476,  576]])

In [38]:
x

array([[3136,   64,  484, 2601, 2916],
       [3844, 3969, 2601, 5929, 2209],
       [ 841,  484, 2116,  121, 8649],
       [9409, 2809, 3481,  121,  225],
       [8836, 5625, 7744, 5476,  576]])

In [39]:
x

array([[56,  8, 22, 51, 54],
       [62, 63, 51, 77, 47],
       [29, 22, 46, 11, 93],
       [97, 53, 59, 11, 15],
       [94, 75, 88, 74, 24]])

In [40]:
x = np.mat(x)

In [41]:
type(x)

numpy.matrix

In [42]:
x*x

matrix([[14293,  8189, 10413,  8271,  7507],
        [20744, 13193, 15602, 12899, 13335],
        [14131, 10188, 12709, 10682,  9275],
        [12906,  7121,  9520, 10908, 13741],
        [21900, 13135, 16419, 14127, 18471]])

In [46]:
x@x

array([[18798,  8775, 15545, 12282, 18105],
       [10116,  8184, 12992,  8042, 15296],
       [15841, 10676, 10863, 12762, 14385],
       [20166, 12200, 12779, 14835, 13481],
       [12481,  7191, 12035,  7305, 12571]])

In [47]:
x

array([[85, 44, 23, 86, 41],
       [ 7, 53, 45, 33, 93],
       [95, 58, 46, 26, 26],
       [97,  4, 96, 13, 84],
       [18, 25, 56, 44, 66]])

In [48]:
x*x

array([[7225, 1936,  529, 7396, 1681],
       [  49, 2809, 2025, 1089, 8649],
       [9025, 3364, 2116,  676,  676],
       [9409,   16, 9216,  169, 7056],
       [ 324,  625, 3136, 1936, 4356]])

In [49]:
x/0

<ipython-input-49-034eb0c6102b>:1: RuntimeWarning: divide by zero encountered in true_divide
  x/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [50]:
x**2

array([[7225, 1936,  529, 7396, 1681],
       [  49, 2809, 2025, 1089, 8649],
       [9025, 3364, 2116,  676,  676],
       [9409,   16, 9216,  169, 7056],
       [ 324,  625, 3136, 1936, 4356]])

In [52]:
x@x@x@x

array([[1162028366,  682758925,  949930398,  814291371, 1091346612],
       [ 831840532,  502554284,  691567922,  586904694,  795922782],
       [1014755994,  601489482,  839164779,  713455855,  959244013],
       [1172346778,  691158925,  962621447,  827432740, 1105002831],
       [ 802219710,  476376640,  662821402,  564913164,  765594262]])

In [57]:
y = np.zeros((3,4))

In [58]:
a = np.array([1,2,3,7])

In [59]:
y + a

array([[1., 2., 3., 7.],
       [1., 2., 3., 7.],
       [1., 2., 3., 7.]])

In [74]:
b = np.array([[5,6,7]])

In [75]:
b

array([[5, 6, 7]])

In [76]:
b.shape

(1, 3)

In [77]:
b.reshape(3,1) + y

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [78]:
b

array([[5, 6, 7]])

In [80]:
b.T +y

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [85]:
arr = np.random.randint(4,100,(5,5))

In [86]:
arr

array([[48, 23, 16, 34, 89],
       [39, 36, 38, 90, 34],
       [31, 30, 10, 75, 98],
       [42, 13, 35, 67, 95],
       [67, 61, 73, 37, 44]])

In [88]:
np.log2(arr)

array([[5.5849625 , 4.52356196, 4.        , 5.08746284, 6.47573343],
       [5.28540222, 5.169925  , 5.24792751, 6.4918531 , 5.08746284],
       [4.95419631, 4.9068906 , 3.32192809, 6.22881869, 6.61470984],
       [5.39231742, 3.70043972, 5.12928302, 6.06608919, 6.56985561],
       [6.06608919, 5.93073734, 6.18982456, 5.20945337, 5.45943162]])